# MCU name
MCU = RP2040

# Bootloader selection
FORCE_NKRO = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
PROGRAMMABLE_BUTTON_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes

#DIP_SWITCH_ENABLE = yes